remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- .jekyll-cache
- imgs
- vendor

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme
    
# Site settings
url: "https://tianlinxu312.github.io"
title: "Tianlin Xu Homepage"
description: "About me"
permalink: pretty
logo: "https://github.com/tianlinxu312/tianlinxu312.github.io/raw/main/imgs/mine.jpeg"

# 3. Gem settings
paginate: 5 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: linylinx # jekyll-seo-tag > Owners twitter username
author: TianlinXu # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Tianlin Xu # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/linylinx
    - https://www.linkedin.com/in/tianlinxu/
    - https://github.com/tianlinxu312
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike


# Header nav
navigation_header:
- title: Home
  url: /
- title: Publications
  url: /publications/
- title: Activities
  url: /activities/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
    

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/linylinx
  LinkedIn: https://www.linkedin.com/in/tianlinxu
  GitHub: https://github.com/tianlinxu312

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
